# Configuration for Periphery - Swift dead code analyzer
# https://github.com/peripheryapp/periphery

# Targets to scan
targets:
  - Jarvis

# Source files to analyze
sources:
  - Sources

# Files to exclude from analysis
exclude:
  - "**/*Tests.swift"
  - "**/Tests/**"
  - "**/*Test.swift"
  - "**/*Mock*.swift"
  - "**/*Stub*.swift"
  - "**/Preview Content/**"
  - "**/.build/**"
  - "**/.swiftpm/**"
  - "**/DerivedData/**"

# Retain public declarations
retain_public: true

# Retain @objc annotated declarations
retain_objc_annotated: true

# Retain @objcMembers annotated declarations
retain_objc_accessible: true

# Retain @IBOutlet annotated declarations
retain_iboutlet: true

# Retain @IBAction annotated declarations
retain_ibaction: true

# Retain Codable synthesized declarations
retain_codable_properties: true

# Retain unused protocol function parameters
retain_unused_protocol_func_params: true

# Disable rules
disable_redundant_public_accessibility: false

# Enable aggressive mode for more thorough analysis
aggressive: false

# Verbose output
verbose: false

# Quiet mode (suppress warnings)
quiet: false

# Format output
format: xcode

# Index store path (optional - Periphery will try to find it automatically)
# index_store_path: .build/debug/index/store

# Build configuration
# build_config: debug

# Schemes to build (if using Xcode project)
# schemes:
#   - JarvisDemo

# Report format options
report_include_public: false
report_exclude_tests: true